ONSdigital/eq-questionnaire-schemas

source/jsonnet/england-wales/ccs/blocks/who-lives-here/who_lives_here_section_summary.jsonnet, source/jsonnet/england-wales/household/blocks/who-lives-here/who_lives_here_section_summary.jsonnet, source/jsonnet/northern-ireland/household/blocks/who-lives-here/who_lives_here_section_summary.jsonnet
I have updated the Census schemas so that they use the new `list collector summary` type. This change has been made as part of following [PR](https://github.com/ONSdigital/eq-questionnaire-runner/pull/28).
=> Add list collector summary type to the census schemas

README.md, source/jsonnet/england-wales/individual/blocks/identity-and-health/birth_gender.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/religion.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/sexual_identity.jsonnet
This adds new boolean "voluntary" property to radio answer in certain questions described on [this Trello card](https://trello.com/c/Wu3oraFw/3424-voluntary-questions-m). It requires [this runner branch](https://github.com/ONSdigital/eq-questionnaire-runner/pull/31) to be merged first.
[Quick launcher](https://v3-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&case_type=HI&region_code=GB-ENG&url=https://gist.githubusercontent.com/petechd/01d6264d903a82bba04960ea2bfa5f06/raw/79129cc0723c3f8392d5420e49d7b91ed2c6bf8e/census_individual_gb_eng.json)
Check that clear button and voluntary property works as expected in census schemas. Symlink schemas from this branch with runner local branch as described in README file. Currently, this change is not implemented in N.I. …
=> Add voluntary property to radio answer

scripts/build_schemas.sh, source/jsonnet/england-wales/individual/blocks/personal-details/date_of_birth.jsonnet, source/jsonnet/northern-ireland/individual/blocks/personal-details/date_of_birth.jsonnet
The validation for the `date-of-birth` question on the household and individual schemas needed to be updated to allow dates from 01/01/1906.
Check that the HH and HI schemas for all regions only allow a DOB after 31/12/1905 to be entered.
=> Update date of birth validation (HI/HH)(ENG/WLS/NI)

source/jsonnet/england-wales/census_household.jsonnet, source/jsonnet/england-wales/household/blocks/relationships/relationships_collector.jsonnet, source/jsonnet/england-wales/household/blocks/relationships/relationships_interstitial.jsonnet, source/jsonnet/northern-ireland/census_household.jsonnet, source/jsonnet/northern-ireland/household/blocks/relationships/relationships_collector.jsonnet, source/jsonnet/northern-ireland/household/blocks/relationships/relationships_interstitial.jsonnet
Currently, on the census schemas, if you don't have at least 2 people then the skip condition on the relationship block skips it and take you to the hub. We need to uses the enabled option on the schema instead and remove the skips
=> Add enabled option on relationship section and remove the skips from the blocks

source/jsonnet/england-wales/individual/blocks/employment/job_description.jsonnet
This PR updates the `TextArea` field size for the` job-description` question (ENG/WLS schema) from 8 to 4 rows (the `job-description` question for NI is currently a `TextField` and is to be updated later).
Check the field size for the `job-description` question
=> Update size of text area field for job description question ENG/WLS HH/HI

source/jsonnet/england-wales/household/blocks/visitor/usual_household_address_details.jsonnet
This PR fixes a routing issue in the visitors section (ENG/WLS HH).
Previously the `usual-household-address-details` question was incorrectly routing to the `usual-household-address-other` question rather than the `visitor-summary` page.
Check that both the `usual-household-address-details` and `usual-household-address-other` questions in the visitors section route to the `visitor-summary`.
=> Fix routing issue in visitors section (ENG/WLS)

scripts/run_validator.sh
Temporarily revert the validator branch to: https://github.com/ONSdigital/eq-questionnaire-validator/commit/ef9e236d8428a5661f7e7501323cc29bcf313e4c
I used the last PR branch prior to the breaking change since we don't push the commit hash on master.
Ensure all schemas validate as expected.
=> Temporarily revert validator branch

source/jsonnet/northern-ireland/individual/blocks/employment/job_description.jsonnet
This sets field length attribute to 120 characters in `job-description` answer. NI schemas only.
Check that there is a 120 characters limit in the actual question when running a NI schema.
=> Add text field limit to job description in NISRA

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pull_request.yml
Uploads the built schemas artifacts to a GCS bucket which are available to be referenced by a quick launch link.
If required, a load balancer with a CDN can be set up with a DNS record instead of using the standard google apis link. By default, the objects are cached for 1 hour, therefore, I have set the necessary headers to prevent client-side cache so that the changes are available immediately.
- Make a PR with this base branch and ensure the schemas are uploaded and are available at the link below.
- OR ensure the artifacts from this PR has been uploaded.
- Ensure, new commits overwrite old artifacts.
Schemas artifacts are available at:
```bash
https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch_name>/schemas/en/<schema_name>.json
```
> For this PR, ENG HH: …
=> Upload schemas to GCS on PR

source/jsonnet/northern-ireland/individual/blocks/personal-details/term_time_address.jsonnet, source/jsonnet/northern-ireland/individual/blocks/personal-details/term_time_country_outside_uk.jsonnet
This PR updates the routing from the NISRA `term-time-address` questions so that they route to the `country-of-birth` question rather than the end of the survey.
Check that the routing is correct. 
[Quick Launcher](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/nisra-term-time-routing/schemas/en/census_individual_gb_nir.json)
Schemas artifacts are available at:
```bash
https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/nisra-term-time-routing/schemas/en/census_individual_gb_nir.json
```
=> NISRA term time address routing changes

.github/PULL_REQUEST_TEMPLATE.md, source/jsonnet/england-wales/ccs_household.jsonnet, source/jsonnet/england-wales/census_household.jsonnet, source/jsonnet/northern-ireland/census_household.jsonnet
Turns off the section summaries for non who lives here section in the following schemas:
1. CCS household England
1. CCS household Wales
1. Census household England
1. Census household Wales
1. Census household NI
Test the section summaries for who lives here sections does not appear on the forward journey in the relevant schemas
Schemas artifacts are available at:
```bash
https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch_name>/schemas/en/<schema_name>.json
```
<a href="https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/wlh-turn-off-summaries/schemas/en/census_household_gb_eng.json" target="_blank">household</a> …
=> Turn off section summaries for non WLH sections

.github/PULL_REQUEST_TEMPLATE.md, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/no_religion_other.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/religion_other.jsonnet
Fixed an issue where built JSON schema was missing some routing rules due to some missing commas. In Jsonnet, objects extend other objects so when merging two objects, the right hand side is chosen when fields collide.
Ensure routing rule in the Trello card now works.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-missing-routing-based-on-age/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-missing-routing-based-on-age/schemas/en/cens …
=> NISRA: Fix age based routing for religion questions

source/jsonnet/england-wales/ccs_household.jsonnet, source/jsonnet/england-wales/census_household.jsonnet, source/jsonnet/northern-ireland/census_household.jsonnet, translations/ccs_household_gb_eng.pot, translations/census_household_gb_nir.pot, translations/census_household_gb_wls.pot
This adds new, census-specific text to title, guidance and button of the hub. Non-census schemas with the hub remain the same. The change is described on this [Trello card](https://trello.com/c/dcfsAeIJ). It was configured using this [feature](https://github.com/ONSdigital/eq-questionnaire-runner/pull/117). Affected schemas: ccs, household.
Run tests, check census hub and compare it to test schema's ones(e.g. test_hub_and_spoke.json)
- [] Jsonnet files conform to the latest [style guide](/ONSdigital/eq-questionnaire-schemas/blob/master/style_guide.md)
Schemas artifacts are available at:
```bash
https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch_name>/schemas/en/<schema_name>.json
```
[household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code= …
=> Add changes to the hub

Pipfile, Pipfile.lock, scripts/eq_translations_check.py
- Updates eq-translations to https://github.com/ONSdigital/eq-translations/releases/tag/v3.1.0
- Also update the translation check script to reference the latest version when promoting for an update.
Ensure:
- translation works as expected.
- when eq-translations is out of date, the latest version is display in the helper text.
=> Update translations to v3.1.0

source/jsonnet/england-wales/household/blocks/visitor/usual_household_address_other.jsonnet, source/jsonnet/northern-ireland/household/blocks/visitor/usual_household_address_other.jsonnet
Added field limit 100 to visitor country in Eng, Wls and NI
[trello card](https://trello.com/c/LXEMJPG3)
Change on usual-household-address-other on visitors section 
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-field-limits/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch>/schemas/en/census_individual_gb_eng.json)
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_ …
=> Adding field limit 100 to visitor country

scripts/build_schemas.sh, source/jsonnet/england-wales/ccs_household.jsonnet, source/jsonnet/england-wales/census_household.jsonnet, source/jsonnet/england-wales/census_individual.jsonnet
Updating the `build_schemas` script so that a Welsh version of the CCS schema is created. This will allow for question variants based on the `GB-WLS` region.
Check that the `ccs_household_gb_wls.json` schema is being created
=> Add Welsh CCS schema

source/jsonnet/england-wales/household/blocks/who-lives-here/anyone_else_list_collector.jsonnet, source/jsonnet/england-wales/household/blocks/who-lives-here/anyone_else_temporarily_away_list_collector.jsonnet, source/jsonnet/england-wales/household/blocks/who-lives-here/visitor_list_collector.jsonnet, source/jsonnet/northern-ireland/household/blocks/who-lives-here/anyone_else_list_collector.jsonnet, source/jsonnet/northern-ireland/household/blocks/who-lives-here/anyone_else_temporarily_away_list_collector.jsonnet, source/jsonnet/northern-ireland/household/blocks/who-lives-here/visitor_list_collector.jsonnet, translations/census_household_gb_nir.pot, translations/census_household_gb_wls.pot
The new feature for warning messages has been added to remove person and remove visitor for all household schemas
Check the right schemas have been updated
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-warnings-to-remove-person-visitor-household/schemas/en/census_household_gb_eng.json)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-warnings-to-remove-person-visitor-household/schemas/en/census_household_gb_nir.json)
=> Add warning message to remove person/ visitor for all household schemas

source/jsonnet/england-wales/census_household.jsonnet, source/jsonnet/northern-ireland/census_household.jsonnet, translations/census_household_gb_nir.pot, translations/census_household_gb_wls.pot
HH schemas need the WLH summary title to be customised to be:
'People who live at {display address} and overnight visitors'
Make sure the text has been updated in runner
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-list-summary-title-hh/schemas/en/census_household_gb_eng.json)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-list-summary-title-hh/schemas/en/census_household_gb_nir.json)
=> Update list summary title for Eng/Wls NI schemas WLH

source/jsonnet/northern-ireland/household/blocks/individual/proxy.jsonnet
This fixes a bug described on following [Trello card](https://trello.com/c/ohpvGLAQ). New [validator rule](https://github.com/ONSdigital/eq-questionnaire-validator/pull/44) is added to prevent this from happening in the future.
In quick launch NISRA household schema, when proxy question left unanswered, it should not cause an error anymore.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/nisra-proxy-bug/schemas/en/census_household_gb_nir.json)
=> Fix mismatching answer default and options value

source/jsonnet/england-wales/ccs/blocks/accommodation/respondent_living_at.jsonnet, source/jsonnet/england-wales/ccs/blocks/individual/proxy.jsonnet, source/jsonnet/england-wales/ccs/blocks/who-lives-here/outside_uk_note.jsonnet, source/jsonnet/england-wales/ccs/blocks/who-lives-here/who_to_interview_note.jsonnet, translations/ccs_household_gb_eng.pot
This adds new `interviewer_only` key and refactor titles in ccs schemas as described on [Trello card](https://trello.com/c/OPIjOqUR). New translations has been added. This change only works if your design system is up to date and built using `make load-design-system-templates`.
Use quick launchers below to compare changes. 
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/implement-interviewer-note/schemas/en/ccs_household_gb_eng.json)
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/implement-int …
=> CCS: Add interviewer note

source/jsonnet/england-wales/ccs/blocks/who-lives-here/anyone_else_driver.jsonnet
Fixes a bug where the add/empty list link is not being displayed in the CCS survey.
Changes the question type of the `anyone-else-driver` question to ListCollectorDrivingQuestion.
Adds a `for_list: 'household' keyval pair to the `anyone-else-driver` question.
Check the add/empty list links appear on the CCS survey anyone_else list summary.
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&regi …
=> Fix CCS list collector driving question

source/jsonnet/england-wales/ccs_household.jsonnet, source/jsonnet/england-wales/lib/common_rules.libsonnet
Makes the `Household accommodation` and Final check - other households` section conditional on the list count.
Ensure the `Household accommodation` and Final check - other households` are not shown when the `household` list is empty.
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/ccs-conditional-sections/schemas/en/ccs_household_gb_eng.json)
=> CCS: Make household accommodation and final section conditional

source/jsonnet/england-wales/ccs/blocks/accommodation/government_services.jsonnet, source/jsonnet/england-wales/ccs/blocks/accommodation/self_contained.jsonnet, source/jsonnet/england-wales/ccs/blocks/individual/employment_status.jsonnet, source/jsonnet/england-wales/ccs/blocks/who-lives-here/anyone_else_list_collector.jsonnet, source/jsonnet/england-wales/ccs/blocks/who-lives-here/anyone_else_temp_away_list_collector.jsonnet, source/jsonnet/england-wales/ccs/blocks/who-lives-here/usual_address.jsonnet, translations/ccs_household_gb_wls.pot
Content mop up updates for CSS as described on [this Trello card](https://trello.com/c/ZEaMfKAz).
Check the changes match the [google doc](https://docs.google.com/spreadsheets/d/1JZDyX0RS2nkZj5A4kXvxubdGr_BV2Hk6XGnSRq6AClA/edit#gid=1275715253).
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/ccs-qa-mop-up-2/schemas/en/ccs_household_gb_eng.json)
=> CCS: QA Mop up changes part 2

source/jsonnet/england-wales/household/blocks/individual/location_one_year_ago.jsonnet, source/jsonnet/england-wales/household/blocks/visitor/visitor_usual_address_details.jsonnet, source/jsonnet/england-wales/individual/blocks/employment/business_type.jsonnet, source/jsonnet/england-wales/individual/blocks/employment/depot_address.jsonnet, source/jsonnet/england-wales/individual/blocks/employment/mainly_work_outside_uk.jsonnet, source/jsonnet/england-wales/individual/blocks/employment/workplace_address.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/address_one_year_ago.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/ethnic_group_black_other.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/ethnic_group_mixed_other.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/ethnic_group_other_other.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/other_national_identities.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/other_national_identity.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/passports.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/passports_additional_other.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/passports_other.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/sexual_orientation.jsonnet, source/jsonnet/england-wales/individual/blocks/personal-details/other_address_uk.jsonnet, source/jsonnet/england-wales/individual/blocks/personal-details/term_time_address_uk.jsonnet, source/jsonnet/england-wales/individual/blocks/qualifications/gcse.jsonnet, translations/census_household_gb_wls.pot, translations/census_individual_gb_wls.pot
Updated schemas as per definitions on card spreadsheet.
Confirm changes are as per card. Ignore the change to business-name (this already exists and appears to not be showing due to a bug).
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/qa-content-changes-2/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/qa-content-changes-2/schemas/en/census_individual_gb_eng.json)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?lang …
=> QA Content Changes II

source/jsonnet/northern-ireland/lib/common_rules.libsonnet
The NISRA `schoolYearUnder4` and `schoolYear5AndOver` rules have been updated so that it is based on `30/06/2020` rather than `01/07/20`
Check that the new routing rule is correct as per the Trello card
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-nisra-school-age/schemas/en/census_household_gb_nir.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-nisra-school-age/schemas/en/census_individual_gb_nir.json)
=> Update NISRA School Age Rule

source/jsonnet/northern-ireland/household/blocks/visitor/visitor_usual_address_country.jsonnet, source/jsonnet/northern-ireland/individual/blocks/employment/workplace_country.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/address_one_year_ago_outside_uk.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/country_of_birth_elsewhere.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/ethnic_group_other.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/no_religion_other.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/other_main_language.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/other_national_identities.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/other_national_identity.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/passports_additional_other.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/passports_other.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/religion_other.jsonnet, source/jsonnet/northern-ireland/individual/blocks/personal-details/term_time_country_outside_uk.jsonnet, source/jsonnet/northern-ireland/individual/blocks/school/study_location_country.jsonnet
Adds NISRA lookups to the NI Household and Individual schemas (they were previously using Eng/Wls lookups).
Check that the correct lookups have been added to the questions as per the trello card.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-nisra-lookups/schemas/en/census_household_gb_nir.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-nisra-lookups/schemas/en/census_individual_gb_nir.json)
=> Update NISRA lookup URLs

source/jsonnet/england-wales/individual/blocks/identity-and-health/arrive_in_uk.jsonnet
Make arrive in uk question optional. Routing changes are not needed.
Ensure arrive in uk question is now optional.
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/remove-mandatory-from-arrive-in-uk/schemas/en/census_individual_gb_eng.json)
=> Make arrive in uk question optional

source/jsonnet/england-wales/household/blocks/who-lives-here/people_living_here.jsonnet, source/jsonnet/northern-ireland/household/blocks/who-lives-here/anyone_else_list_collector.jsonnet, translations/census_household_gb_nir.pot, translations/census_household_gb_wls.pot
Update anyone-else-list-collector to the 2021 version. Change described [here](https://trello.com/c/6FpVmmLj).
Use the quick launches and make sure the content is correct.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/change-driver-variant/schemas/en/census_household_gb_eng.json)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/change-driver-variant/schemas/en/census_household_gb_nir.json)
=> Change driver variant on WLH HH

source/jsonnet/england-wales/individual/blocks/personal-details/date_of_birth.jsonnet, source/jsonnet/northern-ireland/individual/blocks/personal-details/date_of_birth.jsonnet
The current earliest validation on DoB is set at 1/1/1906. This needs to be changed to include all respondents who are 115 at the time of Census date (22/03/1905). 
Check that 22/03/1905 is now a valid DOB in the individual/household journey
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-dob-validation/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-dob-validation/schemas/en/census_individual_gb_eng.json)
- …
=> Update DOB validation

source/jsonnet/england-wales/ccs_household.jsonnet, source/jsonnet/england-wales/census_household.jsonnet, source/jsonnet/northern-ireland/census_household.jsonnet
Add IR to all household schemas
Check the IR option is available on each schema
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/implement-ir-hh/schemas/en/census_household_gb_eng.json)
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/implement-ir-hh/schemas/en/ccs_household_gb_eng.json)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/imp …
=> Implement IR feature on HH schema

source/jsonnet/england-wales/census_household.jsonnet, source/jsonnet/northern-ireland/census_household.jsonnet, translations/census_household_gb_nir.pot, translations/census_household_gb_wls.pot
Page titles have now been added to repeating sections
Goto the repeat section and make sure the page title is correctly formatted, it should be ```<block page_title><section page_title> - Census 2021 ```
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-repeat-identifier-to-schemas/schemas/en/census_household_gb_eng.json)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-repeat-identifier-to-schemas/schemas/en/census_household_gb_nir.json)
=> Add repeat identifier to schemas

source/jsonnet/england-wales/census_communal_establishment.jsonnet, source/jsonnet/england-wales/census_household.jsonnet, source/jsonnet/england-wales/census_individual.jsonnet, source/jsonnet/england-wales/individual/blocks/personal-details/establishment_position.jsonnet, source/jsonnet/northern-ireland/census_household.jsonnet, source/jsonnet/northern-ireland/census_individual.jsonnet, source/jsonnet/northern-ireland/individual/blocks/personal-details/establishment_position.jsonnet, translations/census_communal_establishment_gb_wls.pot, translations/census_household_gb_nir.pot, translations/census_household_gb_wls.pot, translations/census_individual_gb_nir.pot, translations/census_individual_gb_wls.pot
This adds some page titles fixes and removes extra twisty from establishment-position. Change is described on [this Trello card](https://trello.com/c/0naqPfrU).
Check page titles on _Personal details_ and _Identity and health_ answers summary pages. Check if twisty has been removed on establishment-position question.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/changes-individual-survey-content/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifac …
=> Fix HI page titles (ENG/WLS/NI) and remove extra definitions

scripts/run_validator.sh, source/jsonnet/northern-ireland/census_household.jsonnet
The IR content on the hub should be configurable and the default set to on; this should be disabled for the NI HH schema.
Use the `add-flag-for-ir` branch from runner. Check that the NI HH schema no longer shows the IR link on the hub, confirm for Eng/Wales it remains oh the hub.
=> NISRA: Remove individual link from hub

source/jsonnet/england-wales/census_communal_establishment.jsonnet, translations/census_communal_establishment_gb_wls.pot
Adds custom final summary content to the CE schemas (ENG/WLS). Minor change was required in runner's partials/summary templates to make this work. [Link to runner change](https://github.com/ONSdigital/eq-questionnaire-runner/pull/321).
Check the custom content is correct as per the [Trello card](https://trello.com/c/7LiItQka).
Use this [runner branch](https://github.com/ONSdigital/eq-questionnaire-runner/pull/321) to test the change.
=> Add custom summary content for CE schemas

source/jsonnet/england-wales/census_communal_establishment.jsonnet, source/jsonnet/england-wales/census_household.jsonnet, source/jsonnet/england-wales/census_individual.jsonnet, source/jsonnet/northern-ireland/census_household.jsonnet, source/jsonnet/northern-ireland/census_individual.jsonnet
Adds the option to send a confirmation email to the Individual, Household and Communal Establishment schemas (Eng/Wls/NI).
Check that there is an option to send a confirmation email on the `Thank You` page
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-confirmation-email-to-schemas/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-confirmation-email-to-schemas/schemas/en/census_individual_gb_eng.json)
- …
=> Add email confirmation to schemas (Eng/Wls/NI)

source/jsonnet/england-wales/individual/blocks/identity-and-health/arrive_in_uk.jsonnet, source/jsonnet/england-wales/individual/blocks/personal-details/date_of_birth.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/arrive_in_country.jsonnet, source/jsonnet/northern-ireland/individual/blocks/personal-details/age_last_birthday.jsonnet, source/jsonnet/northern-ireland/individual/blocks/personal-details/date_of_birth.jsonnet, translations/census_household_gb_nir.pot, translations/census_household_gb_wls.pot, translations/census_individual_gb_nir.pot, translations/census_individual_gb_wls.pot
This changes custom validation error messages as described on [Trello card](https://trello.com/c/fH7EZwVM). 
Use quick launch schemas below and checklist attached to [Trello card](https://trello.com/c/fH7EZwVM).
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/change-validation-content/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/change-validation-content/schemas/en/census_individual_gb_eng.json)
- …
=> Update custom validation error messages HH/HI(Eng/Wls/NI)

source/jsonnet/northern-ireland/individual/blocks/identity-and-health/other_health_conditions.jsonnet, source/jsonnet/northern-ireland/lib/common_rules.libsonnet
This fixes the routing on `other-health-conditions` question in NISRA HH/HI so it routes to `look-after-or-support-others` based on date of birth and census date. For more details check [this Trello card](https://trello.com/c/M7q42is7).
Check two different dates of birth: before or equal to 21/03/2016 and one later than 21/03/2016. They should route differently(`look-after-or-support-others` for 5 and over, summary for less than 5).
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/fix-nisra-dob-routing/schemas/en/census_household_gb_nir.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey …
=> Fix NISRA age based routing

source/jsonnet/northern-ireland/individual/blocks/school/study_location_type.jsonnet
Adds mandatory validation to the study-location-type question for the NI schemas.
Check that the study-location-type question is mandatory.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/make-study-location-mandatory/schemas/en/census_household_gb_nir.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/make-study-location-mandatory/schemas/en/census_individual_gb_nir.json)
=> Make study-location-type mandatory

source/jsonnet/england-wales/household/blocks/relationships/relationships_collector.jsonnet, source/jsonnet/northern-ireland/household/blocks/relationships/relationships_collector.jsonnet
Adds the required actions for the unrelated block to work, now that https://github.com/ONSdigital/eq-questionnaire-runner/pull/389 has merged.
Test the unrelated questions work in the household schemas.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-unrelated-block-actions/schemas/en/census_household_gb_eng.json)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-unrelated-block-actions/schemas/en/census_household_gb_nir.json)
=> Add unrelated block actions

source/jsonnet/england-wales/household/blocks/visitor/visitor_usual_address_details.jsonnet, source/jsonnet/northern-ireland/household/blocks/visitor/visitor_usual_address_details.jsonnet, translations/census_household_gb_nir.pot, translations/census_household_gb_wls.pot
This fixes question text on `visitor-usual-address-details` in both NI and ENG/WLS HH schemas(CCS is already done). Check [trello card](https://trello.com/c/f74UKtwb) for details.
Check HH NI and ENG/WLS schemas `visitor-usual-address-details` below.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch>/schemas/en/census_household_gb_nir.json)
=> Fix visitor usual address details question text

source/jsonnet/england-wales/household/blocks/individual/location_one_year_ago.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/location_one_year_ago.jsonnet, translations/census_household_gb_wls.pot, translations/census_individual_gb_wls.pot
On the `location-one-year-ago` question the last answer option should be `Another address outside the UK` (Eng/Wls)
Check that the answer option has been updated
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-location-one-year-ago/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-location-one-year-ago/schemas/en/census_individual_gb_eng.json)
=> Update answer content for location one year ago question

source/jsonnet/england-wales/individual/blocks/employment/mainly_work_in_uk.jsonnet
The `mainly-work-in-uk` routing rules have been updated so that it routes to `workplace-address`  when workplace-type is unanswered and mainly-work-in-uk is yes or unanswered
Check that the new routing rule matches the above/the trello card.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-mainly-work-in-uk-routing/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-mainly-work-in-uk-routing/schemas/en/census_individual_gb_eng.json)
=> Update mainly-work-in-uk routing rules

source/jsonnet/england-wales/household/blocks/individual/individual_coronavirus_circumstances.jsonnet
Adds the middle name of any person to the piped name on `individual-coronavirus-circumstances` interstitial page  (Household Eng/Wls only), if they share the same first and last names with anyone else in the household.
Use the ENG/WLS Census household schema and check that the middle name is displayed/not displayed as described in the scenarios listed on the Trello card.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-middle-names-to-interstitial-page/schemas/en/census_household_gb_eng.json)
=> Add middle names to individual-coronavirus-circumstances page

source/jsonnet/england-wales/household/blocks/accommodation/number_of_vehicles.jsonnet, source/jsonnet/england-wales/household/blocks/visitor/visitor_usual_address_details.jsonnet, source/jsonnet/england-wales/household/blocks/who-lives-here/any_visitors.jsonnet, source/jsonnet/england-wales/individual/blocks/employment/business_name.jsonnet, source/jsonnet/england-wales/individual/blocks/employment/job_title.jsonnet, source/jsonnet/england-wales/individual/blocks/qualifications/a_level.jsonnet, translations/census_household_gb_wls.pot, translations/census_individual_gb_wls.pot
Minor content changes needed for the Eng/Wls Household and Individual census schemas.
Check that the content changes match the checklist on the Trello card.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-missing-content/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-missing-content/schemas/en/census_individual_gb_eng.json)
=> Add content changes to ENG/WLS HH/HI

source/jsonnet/england-wales/individual/blocks/employment/business_name.jsonnet, translations/census_household_gb_wls.pot, translations/census_individual_gb_wls.pot
Full stops need to be removed from the question description for `business-name` (Eng/Wls) (HH/HI).
Check that the full stops have been removed.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/remove-full-stops/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/remove-full-stops/schemas/en/census_individual_gb_eng.json)
=> Remove full stops from business-name question description (Eng/Wls)

source/jsonnet/england-wales/ccs/blocks/who-lives-here/anyone_related.jsonnet, source/jsonnet/england-wales/ccs_household.jsonnet
The CCS schema is currently broken as we have used a block id (relationships) which will hit the relationships endpoint and then fall over as it is a Question. The block is a standard Question page and should not be hitting the relationships endpoint so the id needs to be changed
Make sure the rename block is working as expected
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-relationship-ccs-to-anyone-related/schemas/en/ccs_household_gb_eng.json)
=> Update relationships id to anyone-related

scripts/resolve_suggestions_urls.py
Updates the lookup suggestions data to v5.2.0. This uses minified JSON and uses cached and gzipped files.
The file location on the CDN has changed from `data` to `eq-lookup-suggestions-data`.
Verify lookups work in runner.
- [-] Jsonnet files conform to the latest [style guide](/ONSdigital/eq-questionnaire-schemas/blob/master/style_guide.md)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-to-v5.2.0-lookup-suggestions-data/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/ …
=> Update to lookup suggestions data v5.2.0

scripts/resolve_suggestions_urls.py
Updates the lookup suggestions url to version 5.3.0 in line with the latest release.
Check that the lookup suggestions data contains the latest [changes](https://github.com/ONSdigital/eq-lookup-suggestions-data/releases/tag/v5.3.0)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-suggestions-url/schemas/en/census_household_gb_nir.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-suggestions-url/schemas/en/census_individual_gb_nir.json)
=> Update suggestions base url to v5.3.0

source/jsonnet/england-wales/individual/blocks/identity-and-health/other_national_identities.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/other_national_identity.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/passports_additional_other.jsonnet, source/jsonnet/england-wales/individual/blocks/identity-and-health/passports_other.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/other_national_identities.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/other_national_identity.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/passports_additional_other.jsonnet, source/jsonnet/northern-ireland/individual/blocks/identity-and-health/passports_other.jsonnet
This adds `allow_multiple` entries booleans on the following look-up pages: `passports-other`, `passports-additional-other`, `other-national-identity`, `other-national-identities`. This change is described on [Trello](https://trello.com/c/xGiARTdL) and it is a follow up to this [PR](https://github.com/ONSdigital/eq-questionnaire-runner/pull/487).
Run validation, check if HH/HI schemas for ENG/WLS and NI (passports-other, passports-additional-other, other-national-identity, other-national-identities look-up pages) allow multiple selection.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/allow-multiple-selection-in-census-schemas/schemas/ …
=> Add allow multiple selection in census schemas

source/jsonnet/northern-ireland/individual/blocks/qualifications/other_qualifications.jsonnet, translations/census_household_gb_nir.pot, translations/census_individual_gb_nir.pot
This changes direct variant's content of other-qualification question and adds `include` panel so both proxy/non-proxy are the same. It is described on [this Trello card](https://trello.com/c/0DThmtiJ).  New translations need to be added to Crowdin.
Check qualifications section's last question (`other-qualifications`) in quick launch schemas below.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/change-nisra-content/schemas/en/census_household_gb_nir.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionna …
=> Fix "other qualifications" question content in NISRA HH/HI

source/jsonnet/england-wales/individual/blocks/personal-details/term_time_location.jsonnet, translations/census_household_gb_wls.pot, translations/census_individual_gb_wls.pot
Removes the coronavirus guidance from the question description for `term-time-location` (Eng/Wls HH/HI).
Check that the question description has been removed.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/remove-content-term-time-location/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/remove-content-term-time-location/schemas/en/census_individual_gb_eng.json)
=> Remove question description from term time location

source/jsonnet/england-wales/ccs/blocks/individual/term_time_location.jsonnet, translations/ccs_household_gb_wls.pot
Removes the coronavirus guidance from the question description for `term-time-location` (CCS). The change is described on this [Trello card](https://trello.com/c/57Zsms8r).
Check that the question description has been removed.
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/remove-content-ccs/schemas/en/ccs_household_gb_eng.json)
=> Remove question description from term time location CCS

translations/cy/ccs_household_gb_wls_cy.po
Adds the latest Welsh translation for CCS.
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch>/schemas/en/census_individual_gb_eng.json)
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch>/sch …
=> Add latest CCS welsh translations

scripts/resolve_suggestions_urls.py
This updates census schemas to point `suggestions_url` at `cdn.census.gov.uk` domain instead of `cdn.eq.census-gcp.onsdigital.uk`.
Check if current version v5.3.0 published data exists and is latest as required by business requirements.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-to-formal-cdn/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-to-formal-cdn/schemas/en/census_individual_gb_eng.json)
- …
=> Update schemas to use formal CDN

scripts/run_validator.sh
Use released validator version v1.0.0 so that future changes to validator don't break the build.
Check the build passes.
- [-] Jsonnet files conform to the latest [style guide](/ONSdigital/eq-questionnaire-schemas/blob/master/style_guide.md)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/use-fixed-validator-version/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/use-fixed-validator-version/schemas/en/census_individual_gb_eng.json)
- …
=> Use released validator v1.0.0

.github/workflows/release.yml
This removes 'notify runner' step from new schemas release workflow and is part of [Remove schemas release and autosquash workflows](https://github.com/ONSdigital/eq-questionnaire-runner/pull/592) work in runner, as described on [this Trello](https://trello.com/c/cPTkbmwI).
Check that notify runner has been removed, make new release in fork.
=> Remove notify runner job from release workflow

schemas/business/en/lcree_0009.json, schemas/business/en/lcree_0010.json
The introduction had duplicated contact us details.
This has been removed.
=> removed duplicated text

schemas/business/en/mbs_0158.json
Fix to `mbs_0158`. Metadata dates were hardcoded for answer `answer20459962-662d-4439-9987-2b89b0ac5479to`. This has not been updated to link to the metadata.
=> Fix to mbs_0158

poetry.lock, pyproject.toml
This changes eq-translations version to the latest (v4.8.0). Required if we want add the introduction block elements to extractable strings.
Compare versions, check latest eq-translations release https://github.com/ONSdigital/eq-translations/releases.
=> Update eq-translations version to v4.8.0

schemas/business/en/qsl_0002.json, schemas/business/en/qsm_0002.json
=> EAR 2361 Update Sand and Gravel schemas

scripts/run_validator.sh
This adds docker compose V2 command syntax (previously hyphenated `docker-compose`) since the old version is no longer supported. More info: https://docs.docker.com/compose/migrate/.
Check if validator steps in actions work as expected.
=> Use v2 version of docker compose command

.github/workflows/release.yml
Updates the release with the appropriate permissions `write`, as the release action was failing to generate the schemas zip file. See failed run: https://github.com/ONSdigital/eq-questionnaire-schemas/actions/runs/13283731695
Also updates the `softprops/action-gh-release` to the latest version.
Check the permissions and the updated library.
=> Update schemas release task with appropriate permissions

scripts/validate_schemas.py
This introduces improvements to our error handling in `validate_schemas` script. It adds logic to increment the failed counter when an exception occurs during schema processing. We also ensure now that schema processing errors are properly counted towards the total failure count and the whole process of capturing errors was simplified.
Verify that the error handling logic correctly increments the failed counter when an exception occurs during schema processing. Test & confirm that the script exits with a non-zero status code if the number of passed schemas does not match the total schemas processed. Nothing changed in logging but you can double check if schema errors are properly logged.
=> Fix validate schemas script
