ONSdigital/eq-questionnaire-schemas

source/jsonnet/england-wales/individual/blocks/employment/business_name.jsonnet
source/jsonnet/england-wales/individual/blocks/employment/employers_business.jsonnet
source/jsonnet/england-wales/individual/blocks/employment/job_description.jsonnet
source/jsonnet/england-wales/individual/blocks/employment/job_title.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/birth_gender.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/sexual_identity.jsonnet

Limits to be added to text fields 
Schemas that needed changing listed on [trello card](https://trello.com/c/AtcdpR00) 
[Quick Launcher](https://staging-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&case_type=HI&region_code=GB-ENG&url=https://gist.githubusercontent.com/lauraedwards1/cb929c5e3b58d2ab3074510a27a0a572/raw/dffc787e556e06da427936de17abf4d11fe03f61/census_individual_gb_eng.json)

Adding max length to eng/wls

---

source/jsonnet/england-wales/household/blocks/visitor/usual_household_address_other.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/country_of_birth_elsewhere.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/ethnic_group_asian_other.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/ethnic_group_black_african.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/ethnic_group_black_other.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/ethnic_group_other_other.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/ethnic_group_white_other.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/language_other.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/national_identity_other.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/passports_additional_other.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/passports_other.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/past_usual_address_outside_uk.jsonnet
source/jsonnet/england-wales/individual/blocks/identity-and-health/religion_other.jsonnet
source/jsonnet/england-wales/individual/blocks/personal-details/another_address_outside_uk.jsonnet
source/jsonnet/england-wales/individual/blocks/personal-details/term_time_address_country_outside_uk.jsonnet

This PR has been raised to add the SAYT lookup urls to the Household and Individual schemas.
Check that the updated questions load the correct lookup data.

Add SAYT lookup urls (HH/HI) (ENG/WLS)

---

source/jsonnet/england-wales/census_communal_establishment.jsonnet
source/jsonnet/england-wales/communal-establishment/blocks/establishment-details/detention_establishment.jsonnet
source/jsonnet/england-wales/communal-establishment/blocks/establishment-details/education_establishment.jsonnet
source/jsonnet/england-wales/communal-establishment/blocks/establishment-details/nature_of_establishment.jsonnet
source/jsonnet/england-wales/communal-establishment/blocks/establishment-details/travel_establishment.jsonnet

Fixes routing in the Communal Establishment schema.
Check that the routing to the `responsible-for-establishment` question follows the [overflow diagram](https://overflow.io/s/VRBYG3?node=c323b3e5)

Fix routing for communal establishment schema

---

source/jsonnet/northern-ireland/individual/blocks/identity-and-health/country_of_birth.jsonnet
source/jsonnet/northern-ireland/individual/blocks/personal-details/marriage_type.jsonnet

This PR removes mandatory validation for the `marriage-type` and `country-of-birth` questions.
Check validation and routing matches the trello card.

NISRA validation changes

---

scripts/build_schemas.sh

There is no communal establishment schema for NIR.

Stop generating NIR communal establishment schema

---

source/jsonnet/england-wales/census_household.jsonnet
source/jsonnet/northern-ireland/census_household.jsonnet
translations/census_household_gb_nir.pot
translations/census_household_gb_wls.pot

This PR updates the list summary titles in HH
Check the changes against https://trello.com/c/ts9AeTko/3810-b-changes-to-wlh-summary-xs
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/list-title-changes-hh/schemas/en/census_household_gb_eng.json)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/list-title-changes-hh/schemas/en/census_household_gb_nir.json)

Update list titles

---

source/jsonnet/england-wales/ccs/blocks/accommodation/accommodation_type.jsonnet
source/jsonnet/england-wales/ccs/blocks/accommodation/own_or_rent.jsonnet
source/jsonnet/england-wales/ccs/blocks/accommodation/who_rent_from.jsonnet
source/jsonnet/england-wales/ccs/blocks/household-check/other_living_accommodation.jsonnet
source/jsonnet/england-wales/ccs/blocks/household-check/separate_household.jsonnet
source/jsonnet/england-wales/ccs/blocks/individual/ethnic_group.jsonnet
source/jsonnet/england-wales/ccs/blocks/individual/ethnic_group_asian.jsonnet
source/jsonnet/england-wales/ccs/blocks/individual/ethnic_group_black.jsonnet
source/jsonnet/england-wales/ccs/blocks/individual/ethnic_group_mixed.jsonnet
source/jsonnet/england-wales/ccs/blocks/individual/ethnic_group_other.jsonnet
source/jsonnet/england-wales/ccs/blocks/individual/ethnic_group_white.jsonnet
source/jsonnet/england-wales/ccs/blocks/individual/past_usual_household_address.jsonnet
source/jsonnet/england-wales/ccs/blocks/visitor/usual_household_address.jsonnet
source/jsonnet/england-wales/ccs/blocks/who-lives-here/any_visitors.jsonnet
source/jsonnet/england-wales/ccs/blocks/who-lives-here/anyone_else_list_collector.jsonnet
source/jsonnet/england-wales/ccs/blocks/who-lives-here/anyone_else_temp_away_list_collector.jsonnet
source/jsonnet/england-wales/ccs/blocks/who-lives-here/outside_uk_note.jsonnet
source/jsonnet/england-wales/ccs/blocks/who-lives-here/primary_person_list_collector.jsonnet
source/jsonnet/england-wales/ccs/blocks/who-lives-here/usual_address_in_uk.jsonnet
source/jsonnet/england-wales/ccs/blocks/who-lives-here/who_lives_here_interstitial.jsonnet
source/jsonnet/england-wales/ccs/blocks/who-lives-here/who_to_interview_note.jsonnet
source/jsonnet/england-wales/ccs_household.jsonnet
translations/ccs_household_gb_eng.pot

CCS changes according to https://docs.google.com/spreadsheets/d/1JZDyX0RS2nkZj5A4kXvxubdGr_BV2Hk6XGnSRq6AClA/edit#gid=635956077
Check all the changes have been done
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/ccs-mop-up/schemas/en/ccs_household_gb_eng.json)

CCS corrections mop-up 1

---

source/jsonnet/england-wales/ccs/blocks/individual/other_census_address.jsonnet
source/jsonnet/england-wales/ccs/blocks/visitor/usual_household_address_details.jsonnet
source/jsonnet/england-wales/ccs/blocks/who-lives-here/any_visitors.jsonnet
source/jsonnet/england-wales/ccs/blocks/who-lives-here/outside_uk_note.jsonnet
translations/ccs_household_gb_wls.pot

CCS Content changes
Changes on speadsheet attached to [Trello Card](https://trello.com/c/IdYW4J9G). Mop up 3.
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/ccs-corrections/schemas/en/ccs_household_gb_eng.json)

CCS Corrections

---

source/jsonnet/northern-ireland/census_household.jsonnet
source/jsonnet/northern-ireland/census_individual.jsonnet
source/jsonnet/northern-ireland/household/blocks/accommodation/accommodation_type.jsonnet
source/jsonnet/northern-ireland/household/blocks/accommodation/adapted_accommodation.jsonnet
source/jsonnet/northern-ireland/household/blocks/accommodation/renewable_energy_systems.jsonnet
source/jsonnet/northern-ireland/household/blocks/accommodation/renewables_energy_systems.jsonnet
source/jsonnet/northern-ireland/household/blocks/accommodation/type_of_house.jsonnet
source/jsonnet/northern-ireland/individual/blocks/employment/hours_worked.jsonnet
source/jsonnet/northern-ireland/individual/blocks/employment/place_of_work_elsewhere.jsonnet
source/jsonnet/northern-ireland/individual/blocks/employment/workplace_address.jsonnet
source/jsonnet/northern-ireland/individual/blocks/employment/workplace_country.jsonnet
source/jsonnet/northern-ireland/individual/blocks/employment/workplace_location.jsonnet
source/jsonnet/northern-ireland/individual/blocks/employment/workplace_outside_northern_ireland.jsonnet
source/jsonnet/northern-ireland/individual/blocks/employment/workplace_type.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/childhood_religion.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/other_health_conditions.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/physical_health_conditions.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/religion.jsonnet
source/jsonnet/northern-ireland/individual/blocks/school/study_location.jsonnet
source/jsonnet/northern-ireland/individual/blocks/school/study_location_country.jsonnet
source/jsonnet/northern-ireland/individual/blocks/school/study_location_in_northern_ireland.jsonnet
source/jsonnet/northern-ireland/individual/blocks/school/study_location_type.jsonnet
source/jsonnet/northern-ireland/individual/blocks/school/travel_to_study_location.jsonnet

Nisra Urls need update in accordance with https://docs.google.com/spreadsheets/d/1BY1zRuVIL7ipsoVjg3V0fJ9vyaiWNH-AnsCC6O-LoKg/edit#gid=573852521
Check the Urls and associated elements have been changed correctly (i.e block, answer, question and routing)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/nisra-urls-update/schemas/en/census_household_gb_nir.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/nisra-urls-update/schemas/en/census_individual_gb_nir.json)

Update Nisra URL's

---

Pipfile
Pipfile.lock
source/jsonnet/england-wales/census_household.jsonnet
source/jsonnet/northern-ireland/census_household.jsonnet
translations/ccs_household_gb_wls.pot
translations/census_household_gb_nir.pot
translations/census_household_gb_wls.pot

Add warning and guidance for submission. Translations had to be updated, and as the hub keys had never been include ccs also was updated when I ran it.
Check the hub messages are correct on completion of the census
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-warning-and-submission-guidance-hub/schemas/en/census_household_gb_eng.json)
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch>/schemas/en/ccs_household_gb_eng.json)
- …

Add submission guidance and warning

---

source/jsonnet/northern-ireland/individual/blocks/employment/workplace_location.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/no_religion_other.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/religion_other.jsonnet
source/jsonnet/northern-ireland/individual/blocks/school/study_location_type.jsonnet
translations/census_household_gb_nir.pot
translations/census_individual_gb_nir.pot

Changes as per QA changes on spreadsheet attached to [trello card](https://trello.com/c/fhmdD6Yt)
Compare with changes requested on spreadsheet 
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/nisra-changes/schemas/en/census_household_gb_nir.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/nisra-changes/schemas/en/census_individual_gb_nir.json)

NISRA QA mop up card

---

scripts/resolve_suggestions_urls.py

Updates the suggestion data version to v5.0.0
Ensure suggestion lists work as expected.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-suggestions-dataset/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-suggestions-dataset/schemas/en/census_individual_gb_eng.json)
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq- …

Update suggestions data version to v5.0.0

---

Pipfile
Pipfile.lock

Update translations to the latest version which includes page_titles in section repeat

Update translations versions to 4.3.0

---

source/jsonnet/northern-ireland/household/blocks/accommodation/adapted_accommodation.jsonnet
source/jsonnet/northern-ireland/household/blocks/individual/location_one_year_ago.jsonnet
source/jsonnet/northern-ireland/household/blocks/relationships/relationships_collector.jsonnet
source/jsonnet/northern-ireland/individual/blocks/employment/hours_worked.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/arrive_in_country.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/childhood_religion.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/childhood_religion_other.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/ethnic_group.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/ethnic_group_other.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/location_one_year_ago.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/look_after_or_support_others.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/physical_health_conditions.jsonnet
source/jsonnet/northern-ireland/individual/blocks/identity-and-health/religion_other.jsonnet
source/jsonnet/northern-ireland/individual/blocks/qualifications/gcse.jsonnet
source/jsonnet/northern-ireland/individual/blocks/school/study_location_type.jsonnet
translations/census_household_gb_nir.pot
translations/census_individual_gb_nir.pot

This adds latest NI schemas content changes and translations described on [the trello card](https://trello.com/c/VoTDGwJJ).
Run quick launch schema, refer to Google docs "QA CHANGES" tab.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/nisra-qa-changes/schemas/en/census_household_gb_nir.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/nisra-qa-changes/schemas/en/census_individual_gb_nir.json)

Add NISRA QA content changes

---

scripts/validate_schemas.sh
translations/cy/census_communal_establishment_gb_wls_cy.po

Updates the CE welsh `.po` file with the latest translations 
Check that all CE content has been translated to Welsh

Add Welsh CE translations

---

source/jsonnet/england-wales/census_communal_establishment.jsonnet
source/jsonnet/england-wales/census_household.jsonnet
source/jsonnet/england-wales/census_individual.jsonnet
source/jsonnet/northern-ireland/census_household.jsonnet
source/jsonnet/northern-ireland/census_individual.jsonnet

Add feedback property to submission property in HH, HI schemas for Eng, Wls and NI and CE schemas for Eng & Wls
Check feedback has been added
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-feeback-to-schemas/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/add-feeback-to-schemas/schemas/en/census_individual_gb_eng.json)
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code …

Add Feedback to schemas

---

source/jsonnet/england-wales/household/blocks/who-lives-here/people_living_here.jsonnet
source/jsonnet/england-wales/household/blocks/who-lives-here/people_who_live_here_introduction.jsonnet
source/jsonnet/northern-ireland/household/blocks/who-lives-here/people_living_here.jsonnet
translations/census_household_gb_nir.pot
translations/census_household_gb_wls.pot

Content corrections
Make sure the changes have been done according to https://trello.com/c/4AOdVHVQ/4290-p1-wlh-incorrect-content
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/wlh-incorrect-content/schemas/en/census_household_gb_eng.json)
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/wlh-incorrect-content/schemas/en/census_household_gb_nir.json)

WLH - incorrect content

---

translations/cy/census_communal_establishment_gb_wls_cy.po

Updates the translations for CE
Ensure the translation file matches the one in Crowdin.

Update CE translations

---

.github/workflows/pull_request.yml
.github/workflows/release.yml

Remove set env from Github actions
Check workflows correctly execute
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch>/schemas/en/census_individual_gb_eng.json)
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch>/schemas/en/ccs …

Remove set-env from GitHub Actions

---

scripts/resolve_suggestions_urls.py

Updates the suggestion data version to v5.1.0
Ensure suggestion lists work as expected.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-lookup-version/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-lookup-version/schemas/en/census_individual_gb_eng.json)
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionna …

Update suggestions data url to version 5.1.0

---

translations/cy/census_communal_establishment_gb_wls_cy.po

Adds the latest Welsh translations for the Communal Establishment survey from Crowdin.
Check that the translations match Crowdin

Add latest CE translations

---

translations/cy/census_household_gb_wls_cy.po

Updates the household `.po` file with the latest translations in Welsh (cy) from Crowdin.

Add latest Welsh translations for the household schema (cy)

---

translations/cy/census_household_gb_wls_cy.po

Adds the latest fixes from crowdin to the Welsh household schema.
Check the translated strings match crowdin

Add latest Welsh household translation fixes

---

translations/cy/census_household_gb_wls_cy.po

Updated translation from Crowdin to fix a spacing issue.
Check the updated translation matches Crowdin

Fix spacing issue in Welsh household .po file

---

source/jsonnet/northern-ireland/individual/blocks/employment/workplace_type.jsonnet
source/jsonnet/northern-ireland/individual/blocks/school/study_location_type.jsonnet
translations/census_household_gb_nir.pot
translations/census_individual_gb_nir.pot

Add content changes as described on [this trello card](https://trello.com/c/jRBaWdqM).
Check quick launcher schemas, refer to trello card.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch>/schemas/en/census_household_gb_nir.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch>/schemas/en/census_individual_gb_nir.json)

Nisra content changes: workplace-type and study-location-type questions

---

translations/cy/census_individual_gb_wls_cy.po

Updates the individual `.po` file with the latest translations in Welsh (cy) from Crowdin.

Add latest Welsh translations for the individual schema (cy)

---

translations/cy/census_individual_gb_wls_cy.po

Updates the individual `.po` file with the latest translations in Welsh (cy) from Crowdin.

Add Welsh translations fix for the individual schema (cy)

---

translations/cy/ccs_household_gb_wls_cy.po

Updates the CSS schema `.po` file with the latest translations in Welsh (cy) from Crowdin.

Add latest Welsh translations for the CCS schema (cy)

---

translations/cy/census_household_gb_wls_cy.po
translations/cy/census_individual_gb_wls_cy.po

Updates the individual & household `.po` file with the latest translations in Welsh (cy) from Crowdin.

Add latest Welsh translations for the HH/HI schemas (cy)

---

translations/cy/census_household_gb_wls_cy.po
translations/cy/census_individual_gb_wls_cy.po

What is the context of this PR?
Updates the individual & household .po file with the latest translations in Welsh (cy) from Crowdin.
How to review

Add latest Welsh translations for the Census HH/HI schemas

---

translations/eo/census_household_gb_nir_eo.po
translations/eo/census_individual_gb_nir_eo.po

Updates the individual & household .po file with the latest translations in Ulster Scots (eo) from Crowdin.

Add latest Ulster Scots translations for the Census HH/HI schemas

---

translations/ga/census_household_gb_nir_ga.po
translations/ga/census_individual_gb_nir_ga.po

Updates the individual & household .po file with the latest translations in Irish (ga) from Crowdin.

Add latest Irish translations for the Census HH/HI schemas

---

translations/cy/ccs_household_gb_wls_cy.po

Updates the CSS translations to match Crowdin.
Ensure the translations match what is in Crowdin.
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-ccs-po/schemas/en/ccs_household_gb_eng.json)

Update CCS translations

---

translations/eo/census_household_gb_nir_eo.po
translations/eo/census_individual_gb_nir_eo.po

Adds the latest Ulster Scots translations.
Check the translations match crowdin.

Add latest Ulster Scots translations

---

translations/ga/census_household_gb_nir_ga.po
translations/ga/census_individual_gb_nir_ga.po

Adds the latest Gaelic translations

Add latest gaelic translations

---

translations/eo/census_household_gb_nir_eo.po

Updates the household .po file with the latest translations in Ulster Scots (eo) from Crowdin.

Add latest Ulster Scots HH schema translations

---

scripts/resolve_suggestions_urls.py

Update lookup suggestions data to v5.4.0 - https://github.com/ONSdigital/eq-lookup-suggestions-data/releases/tag/v5.4.0
Test the built schemas in runner.
- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-lookup-suggestions-data-v5.4.0/schemas/en/census_household_gb_eng.json)
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/update-lookup-suggestions-data-v5.4.0/schemas/en/census_individual_gb_eng.json)
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_cod …

Update lookup suggestions data to v5.4.0

---

scripts/resolve_suggestions_urls.py

Update eq-lookup-suggestions-data to v5.5.0
Test the build locally
- [Individual](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch>/schemas/en/census_individual_gb_eng.json)
- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/<branch>/schemas/en/ccs_h …

Update eq-lookup-suggestions-data to v5.5.0

---

Pipfile.lock

This updates all dependencies (included latest urllib3 version). Change is described on [this Trello](https://trello.com/c/GAzw4iAJ).
To test run all makefile scripts (build, test, linting, formatting, translations). Run validation script and use local version of [eq-questionnaire-validator](https://github.com/ONSdigital/eq-questionnaire-validator) to verify if schemas are checked without issues.

Update package dependencies

---

scripts/run_validator.sh

Update to v3.3.0

---

schemas/business/en/lcree_0010.json

Changed theme to Northern Ireland

---

schemas/business/en/lcree_0009.json
schemas/business/en/lcree_0010.json

removed extra metadata

---

schemas/business/en/lcree_0009.json
schemas/business/en/lcree_0010.json

added optional trad-as

---

schemas/business/en/2_0001.json

Added schema for qbs

---

scripts/run_validator.sh

Most recent version of validator for QBS

Bumping to v3.4.0 of validator

---

schemas/business/en/2_0001.json

new version of qbs

---

schemas/business/en/2_0001.json
scripts/run_validator.sh

update for QBS banner

---

schemas/business/en/2_0001.json

updated QBS wording

---

schemas/business/en/2_0001.json

EAR- 1662 Changes to QBS

---

schemas/business/en/2_0001.json

QBS update

---

schemas/business/en/cat_0001.json
schemas/business/en/cat_0002.json

EAR 1736 Construction

---

schemas/business/en/construction_0001.json
schemas/business/en/construction_0002.json

Update to both `construction_0001` and `construction_00002`
Check all valid values are changed.

Changes to construction

---

schemas/business/en/construction_0001.json
schemas/business/en/construction_0002.json

removed trad_as

---

schemas/business/en/qpses160_0002.json
schemas/business/en/qpses165_0002.json
schemas/business/en/qpses169_0003.json

EAR 1755 QPSES

---

schemas/business/en/qpses165_0002.json

EAR-1755-qpses-to-gcp-changes-165

---

scripts/run_validator.sh

Updates validator to the latest release
Ensure schemas pass validation

Validator 3.6.0

---

schemas/business/en/covid_0001.json

EAR 1770 Add BICS changes

---

schemas/business/en/covid_0001.json

Ear 1780 bics wave61

---

schemas/business/en/vacancies182_0006.json
schemas/business/en/vacancies183_0006.json
schemas/business/en/vacancies184_0006.json
schemas/business/en/vacancies185_0005.json

EAR 1791 Add vacancies surveys

---

schemas/business/en/1_0005.json

EAR-1793 MWSS

---

schemas/business/en/covid_0002.json

EAR-1794 BICS

---

schemas/business/en/qfs_0002.json

Fuels Survey - remove group title

---

schemas/business/en/construction_0001.json

construction - remove group title

---

schemas/business/en/covid_0001.json

EAR 1803 BICS wave 63

---

schemas/business/en/covid_0002.json

covid 0002

---

schemas/business/en/mbs_0106.json
schemas/business/en/mbs_0111.json
schemas/business/en/mbs_0117.json
schemas/business/en/mbs_0123.json
schemas/business/en/mbs_0158.json
schemas/business/en/mbs_0161.json
schemas/business/en/mbs_0167.json
schemas/business/en/mbs_0173.json
schemas/business/en/mbs_0201.json
schemas/business/en/mbs_0202.json
schemas/business/en/mbs_0203.json
schemas/business/en/mbs_0204.json
schemas/business/en/mbs_0205.json
schemas/business/en/mbs_0216.json
schemas/business/en/mbs_0251.json
schemas/business/en/mbs_0255.json
schemas/business/en/mbs_0817.json
schemas/business/en/mbs_0823.json
schemas/business/en/mbs_0867.json
schemas/business/en/mbs_0873.json

Adding the new MBS surveys to GCP.
https://jira.ons.gov.uk/browse/EAR-1816

MBS Surveys added to GCP

---

schemas/business/en/mbs_0158.json
schemas/business/en/mbs_0161.json
schemas/business/en/mbs_0167.json
schemas/business/en/mbs_0173.json
schemas/business/en/mbs_0202.json
schemas/business/en/mbs_0251.json
schemas/business/en/mbs_0253.json
schemas/business/en/mbs_0255.json
schemas/business/en/mbs_0867.json
schemas/business/en/mbs_0873.json

EAR 1819 Redeploy MBS

---

schemas/business/en/mbs_0106.json
schemas/business/en/mbs_0111.json
schemas/business/en/mbs_0117.json
schemas/business/en/mbs_0123.json
schemas/business/en/mbs_0201.json
schemas/business/en/mbs_0202.json
schemas/business/en/mbs_0203.json
schemas/business/en/mbs_0204.json
schemas/business/en/mbs_0205.json
schemas/business/en/mbs_0216.json
schemas/business/en/mbs_0817.json
schemas/business/en/mbs_0823.json

remove metadata

---

scripts/run_validator.sh

Validator v3.9.0 (q_code validation disabled)
Needed for #296 
Ensure schemas validate

Validator v3.9.0

---

schemas/business/en/covid_0001.json

BICS Wave 65

---

schemas/business/en/stocks_0001.json
schemas/business/en/stocks_0002.json
schemas/business/en/stocks_0003.json
schemas/business/en/stocks_0004.json
schemas/business/en/stocks_0005.json
schemas/business/en/stocks_0006.json
schemas/business/en/stocks_0007.json
schemas/business/en/stocks_0008.json
schemas/business/en/stocks_0009.json
schemas/business/en/stocks_0010.json
schemas/business/en/stocks_0011.json
schemas/business/en/stocks_0012.json
schemas/business/en/stocks_0013.json
schemas/business/en/stocks_0014.json
schemas/business/en/stocks_0033.json
schemas/business/en/stocks_0034.json
schemas/business/en/stocks_0051.json
schemas/business/en/stocks_0052.json
schemas/business/en/stocks_0057.json
schemas/business/en/stocks_0058.json
schemas/business/en/stocks_0061.json
schemas/business/en/stocks_0070.json

Signed-off-by: sudeep <sudeep.kunhikannan@ons.gov.uk>

EAR-1828 - Add stocks surveys

---

schemas/business/en/2_0001.json

Signed-off-by: sudeep <sudeep.kunhikannan@ons.gov.uk>

EAR-1830 - Edited 2_0001.json with the new schema

---

schemas/business/en/covid_0002.json

EAR 1831 Bics 66

---

schemas/business/en/epe_0003.json
schemas/business/en/epe_0004.json

EAR-1833 Publish EPE

---

schemas/business/en/covid_0001.json

EAR 1851 Add BICS 67

---

schemas/business/en/covid_0002.json

EAR 1867 - BICS wave 68 

---

schemas/business/en/covid_0002.json

EAR 1867 BICS 68 redeploy

---

schemas/business/en/covid_0001.json

Signed-off-by: sudeep <sudeep.kunhikannan@ons.gov.uk>

EAR-1892 - Publish BICS wave 69

---

schemas/business/en/covid_0001.json

EAR 1892 BICS redeploy

---

schemas/business/en/covid_0002.json

This PR is linked to this Jira ticket https://jira.ons.gov.uk/browse/EAR-1907

EAR-1907 - Publish bics wave 70

---

schemas/business/en/acas_0002.json
schemas/business/en/acas_0003.json

EAR 1909 ACAS

---

docker-compose-schema-validator.yml
scripts/run_validator.sh

This updates validator version used in script and docker file to v3.10.0. That version includes few changes: poetry update, upgrades python to 3.10 and  reintroduces q_codes validation.
Check that it builds and validates correctly.

Update validator version to v3.10.0

---

schemas/business/en/covid_0001.json

This PR is linked to this Jira [ticket](https://jira.ons.gov.uk/browse/EAR-1916)

EAR-1916-publish-bics-wave-71

---

schemas/business/en/1_0112.json
schemas/business/en/1_0213.json
schemas/business/en/1_0215.json
schemas/business/en/abs_1802.json
schemas/business/en/abs_1804.json
schemas/business/en/abs_1808.json
schemas/business/en/abs_1810.json
schemas/business/en/abs_1812.json
schemas/business/en/abs_1814.json
schemas/business/en/abs_1818.json
schemas/business/en/abs_1820.json
schemas/business/en/abs_1824.json
schemas/business/en/abs_1826.json
schemas/business/en/abs_1862.json
schemas/business/en/abs_1864.json
schemas/business/en/abs_1874.json

https://jira.ons.gov.uk/browse/EAR-1917

EAR-1917 - Redeploy rsi and abs schemas

---

schemas/business/en/abs_1804.json
schemas/business/en/abs_1808.json
schemas/business/en/abs_1810.json
schemas/business/en/abs_1812.json
schemas/business/en/abs_1814.json
schemas/business/en/abs_1818.json
schemas/business/en/abs_1820.json
schemas/business/en/abs_1824.json
schemas/business/en/abs_1826.json
schemas/business/en/abs_1862.json
schemas/business/en/abs_1864.json
schemas/business/en/abs_1874.json

This PR is linked to this [jira ticket](https://jira.ons.gov.uk/browse/EAR-1922)

EAR-1922-redeploy-abs-schemas

---

schemas/business/en/abs_1874.json

Signed-off-by: sudeep <sudeep.kunhikannan@ons.gov.uk>
This is to redeploy ABS1874 only - set all questions as mandatory except the last one.
https://jira.ons.gov.uk/browse/EAR-1922

EAR-1922 - Redeploy ABS1874 - Set mandatory questions

---

schemas/business/en/covid_0002.json

This PR is linked to this [Jira ticket](https://jira.ons.gov.uk/browse/EAR-1924)

EAR-1924-Publish-bics-wave-72

---

schemas/business/en/lcree_0009.json
schemas/business/en/lcree_0010.json

This PR is linked to this [Jira ticket](https://jira.ons.gov.uk/browse/EAR-1937)

EAR-1937-publish-low-carbon-to-gcp

---

schemas/business/en/covid_0002.json

BICS wave 74

---

schemas/health/en/phm_0001.json

Removed metadata

---

schemas/business/en/ukis_0001.json
schemas/business/en/ukis_0002.json

This PR is linked to [this Jira ticket](https://jira.ons.gov.uk/browse/EAR-1980)

EAR-1980-republish-ukis-2nd

---

schemas/business/en/covid_0002.json

https://jira.ons.gov.uk/browse/EAR-1986

EAR-1986 - Publish BICS Wave 76

---

schemas/health/en/phm_0001.json

updated PHM with answer codes

---

schemas/business/en/berd_0001.json

Add berd survey

---

schemas/health/en/phm_0001.json
translations/phm_0001.pot

re-publish the PHM schema to the repo
[Jira EAR-1994](https://jira.ons.gov.uk/browse/EAR-1994)
Changes:
1. Theme from social to Health.
2. Form type set to 0001
Note:
- No trad_as
- No employment_date

EAR-1994 Publish PHM Schema.

---

schemas/business/en/covid_0001.json

Publish BICS Wave 77 to pre-prod
[Jira ticket](https://jira.ons.gov.uk/browse/EAR-1999)

EAR-1999 BICS to pre prod

---

schemas/business/en/073_0001.json
schemas/business/en/074_0001.json

This PR is linked to this [Jira ticket](https://jira.ons.gov.uk/browse/EAR-2001)

EAR-2001-deploy-bricks-and-blocks

---

Makefile
README.md
scripts/extract_translation_templates.py
scripts/translate_schemas.py

The CRIS survey also needs to support translations therefore, this updates the translation mappings.
Ensure schemas named `cris_*` can be extracted and translated.

Support extraction and translation of the CRIS survey

---

schemas/business/en/073_0001.json
schemas/business/en/074_0001.json

Publish the Bricks and Blocks to pre-prod
[Jira Ticket EAR-2019](https://jira.ons.gov.uk/browse/EAR-2019)

EAR-2019 publish the Bricks and Blocks to pre-prod

---

schemas/health/cy/phm_0001.json
translations/health/cy/phm_0001.po

Translate phm_0001.json to CY and publish it

---

schemas/business/en/abs_1808.json

EAR 1992 Republish ABS 1808

---

schemas/business/en/073_0002.json
schemas/business/en/074_0002.json

This PR is linked to this [Jira ticket](https://jira.ons.gov.uk/browse/EAR-2023)
-Check that the form type has been updated

EAR-2023-republish-bricks-and-blocks

---

schemas/business/en/berd_0001.json

This PR is linked to this [Jira ticket](https://jira.ons.gov.uk/browse/EAR-2022)

EAR-2022-publish-berd-to-pre-prod

---

schemas/business/en/abs_1814.json
schemas/business/en/abs_1824.json

Fix to q-code and a label for ABS

fix to ABS

---

schemas/business/en/acas_0002.json
schemas/business/en/acas_0003.json

Fix acas dates and use new format for calculated summaries

fix acas dates

---

schemas/business/en/covid_0001.json

Publish BICS wave 79 to repo
Jira [Ticket](https://jira.ons.gov.uk/browse/EAR-2032)

Publish to repo

---

schemas/business/en/aris_0001.json

This PR is linked to this [Jira ticket](https://jira.ons.gov.uk/browse/EAR-2049)

EAR-2049-publish-railways-survey

---

schemas/business/en/covid_0002.json

EAR 2052 BICS wave 80

---

schemas/business/en/ukis_0001.json
schemas/business/en/ukis_0002.json

EAR 2054 Publish UKIS

---

schemas/business/en/berd_0001.json
schemas/business/en/berd_0006.json

This PR is linked to this [Jira ticket](https://jira.ons.gov.uk/browse/EAR-2063)

EAR-2063-publish-berd-to-pre-prod

---

schemas/business/en/covid_0001.json

This PR is linked to this [Jira ticket](https://jira.ons.gov.uk/browse/EAR-2071)

EAR-2071-publish-bics-to-pre-prod

---

schemas/business/en/berd_0001.json

[Jira ticket EAR-2084](https://jira.ons.gov.uk/browse/EAR-2084)

Update BERD schema

---

schemas/business/en/covid_0001.json

Ear 2087 publish bics wave 83

---

poetry.lock
schemas/health/cy/cris_0001.json
translations/health/cy/cris_0001.po

Updates the translations for CRIS schema.
Trello card is [here](https://trello.com/c/5Ct4e8SF/5728-generate-update-welsh-schema-for-phm-cris-1-sp)
Run make `translate-schemas` and ensure the change is identical.
You may want to download the `cris_0001.po` file from the Trello card yourself and translate the schema to test it is the same.

Update PHM/CRIS Welsh translations

---

schemas/health/cy/cris_0001.json
translations/health/cy/cris_0001.po

Reverts ONSdigital/eq-questionnaire-schemas#406

Revert "Update PHM/CRIS Welsh translations"

---

schemas/health/en/cris_0001.json
translations/cris_0001.pot

Reverts ONSdigital/eq-questionnaire-schemas#405

Revert "EAR-2102 CRIS Create pot file"

---

schemas/business/en/berd_0001.json

This PR is linked to this [Jira ticket](https://jira.ons.gov.uk/browse/EAR-2113)

EAR-2113-republish-berd-into-pre-prod

---

schemas/health/en/cris_0001.json
translations/cris_0001.pot

Reverts ONSdigital/eq-questionnaire-schemas#408

Revert "Revert "EAR-2102 CRIS Create pot file""

---

schemas/health/cy/cris_0001.json
translations/health/cy/cris_0001.po

Reverts ONSdigital/eq-questionnaire-schemas#407

Revert "Revert "Update PHM/CRIS Welsh translations""

---

schemas/business/en/covid_0001.json

EAR 2116 Publish BICS wave 85

---

schemas/business/en/covid_0002.json

This PR is linked to this [Jira ticket](https://jira.ons.gov.uk/browse/EAR-2145)

EAR-2145-publish-bics-wave-86

---

README.md
scripts/validate_schemas.sh

What it says on the tin.
Also:
- Some readme syntax highlighting additions
- Updates status endpoint to hit 5002 as that is AJV (same as runner)
Follow the readme and ensure you can validate a single schema while maintaining existing functionality.

Support validating a single schema

---

schemas/business/en/covid_0002.json

Jira [ticket](https://jira.ons.gov.uk/browse/EAR-2183)

Publish BICS wave 88

---

schemas/business/en/covid_0001.json

EAR 2236 Add BICS 89

---

schemas/business/en/covid_0002.json

EAR 2243 BICS 90

---

schemas/business/en/mcg_0001.json
schemas/business/en/mcg_0002.json

Publish Monthly Survey of Consumer Credit Grantors for GB and NI

EAR Publish GB NI MCG

---

schemas/business/en/covid_0002.json

EAR 2257 Add BICS 92

---

schemas/business/en/covid_0002.json

EAR 2257 Update BICS

---

schemas/business/en/covid_0001.json

EAR 2260 BICS 93

---

schemas/business/en/abs_1879.json

EAR 2262 Pub ABS 1879 Animal Husbandry and Hunting

---

schemas/business/en/epe_0003.json
schemas/business/en/epe_0004.json

Jira [ticket](https://jira.ons.gov.uk/browse/EAR-2261)

Ear 2261 publish epe

---

schemas/business/en/epe_0003.json
schemas/business/en/epe_0004.json

EAR 2261 Republish EPE

---

schemas/health/en/fuis_0001.json

EAR 2303 publish follow up WICS

---

schemas/health/en/wcis_0001.json

[EAR-2295](https://jira.ons.gov.uk/browse/EAR-2295)

EAR-2295 - Publish Winter CIS

---

schemas/health/en/wcis_0001.json

EAR 2295 Publish Winter CIS

---

schemas/business/en/covid_0002.json

Jira [Ticket](https://jira.ons.gov.uk/browse/EAR-2309)

Publish Bics wave 96

---

schemas/business/en/covid_0001.json

https://jira.ons.gov.uk/browse/EAR-2315

EAR-2315 - Publish BICS w97

---

schemas/business/en/covid_0002.json

https://jira.ons.gov.uk/browse/EAR-2320

EAR-2320 - Publish BICS w98

---

schemas/business/en/qrt_0001.json

EAR 2324 Update roofing tiles

---

schemas/business/en/covid_0001.json

https://jira.ons.gov.uk/browse/EAR-2325

EAR-2325 - Publish BICS w99

---

schemas/business/en/covid_0002.json

https://jira.ons.gov.uk/browse/EAR-2326

EAR-2326 - Publish BICS wave 100

---

schemas/health/en/wcis_0001.json

https://jira.ons.gov.uk/browse/EAR-2327

EAR-2327 - Re-publish WCIS

---

schemas/business/en/bricks_0002.json
schemas/business/en/bricks_0003.json

[Jira Ticket](https://jira.ons.gov.uk/browse/EAR-2330)

Publish Bricks

---

schemas/business/en/qs_0002.json

https://jira.ons.gov.uk/browse/EAR-2329

EAR-2329-publish-slate-testing

---

schemas/business/en/qrt_0001.json

https://jira.ons.gov.uk/browse/EAR-2328

EAR-2328 - Redeploy roofing tiles

---

schemas/health/en/fuis_0001.json

EAR 2334 Update FUIS

---

schemas/business/en/covid_0001.json

https://jira.ons.gov.uk/browse/EAR-2335

EAR-2335 - Publish BICS w101

---

schemas/business/en/qrt_0003.json

EAR 2338 Add bricks

---

schemas/business/en/qrt_0002.json

EAR 2339 Add slate

---

schemas/business/en/abs_1801.json
schemas/business/en/abs_1803.json
schemas/business/en/abs_1805.json
schemas/business/en/abs_1806.json
schemas/business/en/abs_1807.json
schemas/business/en/abs_1809.json
schemas/business/en/abs_1811.json
schemas/business/en/abs_1813.json
schemas/business/en/abs_1815.json
schemas/business/en/abs_1817.json
schemas/business/en/abs_1819.json
schemas/business/en/abs_1821.json
schemas/business/en/abs_1823.json
schemas/business/en/abs_1825.json
schemas/business/en/abs_1827.json
schemas/business/en/abs_1861.json
schemas/business/en/abs_1863.json
schemas/business/en/abs_1865.json
schemas/business/en/abs_1867.json
schemas/business/en/abs_1869.json
schemas/business/en/abs_1871.json
schemas/business/en/abs_1873.json
schemas/business/en/abs_1875.json
schemas/business/en/abs_1877.json
schemas/business/en/abs_1879.json

https://jira.ons.gov.uk/browse/EAR-2337

EAR-2337 - Publish ABS

---

schemas/business/en/qrt_0001.json

EAR-2340-Publish-Tiles

---

schemas/business/en/qrt_0002.json

EAR-2341-Slate-survey

---

schemas/business/en/qrt_0003.json

EAR-2342-Brick-Survey

---

schemas/business/en/lcree_0009.json
schemas/business/en/lcree_0010.json

https://jira.ons.gov.uk/browse/EAR-2346

EAR-2346 - Publish LCREE GB and NI forms

---

schemas/business/en/acas_0002.json
schemas/business/en/acas_0003.json

Update ACAS schemas

---

schemas/business/en/qrt_0001.json
schemas/business/en/qrt_9001.json

EAR 2355 Update Roofing Tiles schema

---

schemas/business/en/covid_0001.json

https://jira.ons.gov.uk/browse/EAR-2358

EAR-2358 - Publish BICS for survey 283 and form type 0001

---

schemas/business/en/qsm_0002.json

https://jira.ons.gov.uk/browse/EAR-2359

EAR-2359 - Publish Sand and Gravel for survey 076 and form type 0002

---

schemas/business/en/qsl_0002.json

https://jira.ons.gov.uk/browse/EAR-2360

EAR-2360 - Publish Sand and Gravel Land-won for survey 066 and form type 0002

---

schemas/business/en/qs_0001.json

https://jira.ons.gov.uk/browse/EAR-2363
https://jira.ons.gov.uk/browse/EAR-2364

EAR-2363 - Publish Slate and Tiles - Surveys 068, 071 and form type 0001

---

schemas/business/en/covid_0002.json

Publish BICS w104 
Ticket: https://jira.ons.gov.uk/browse/EAR-2369

EAR-2369 Publish BICS w104

---

schemas/business/en/abs_1802.json
schemas/business/en/abs_1804.json
schemas/business/en/abs_1808.json
schemas/business/en/abs_1810.json
schemas/business/en/abs_1812.json
schemas/business/en/abs_1814.json
schemas/business/en/abs_1818.json

[Jira Ticket ](https://jira.ons.gov.uk/browse/EAR-2376)

EAR-2376 Update ABS schemas

---

schemas/business/en/abs_1820.json
schemas/business/en/abs_1824.json
schemas/business/en/abs_1826.json
schemas/business/en/abs_1862.json
schemas/business/en/abs_1864.json
schemas/business/en/abs_1874.json

EAR-2377 Publish ABS Part 2

---

schemas/business/en/abs_1867.json

https://jira.ons.gov.uk/browse/EAR-2380

EAR-2380 - Publish ABS (Shipbuilding) - Survey 202 and form type 1867

---

schemas/business/en/covid_0001.json

Publish BICS wave 105

---

schemas/business/en/covid_0002.json

Publish BICS w106 : https://jira.ons.gov.uk/browse/EAR-2393

EAR-2393 Publish BICS w106

---

schemas/business/en/covid_0001.json

EAR-2399 - Update to BICS

---

schemas/business/en/abs_1818.json

https://jira.ons.gov.uk/browse/EAR-2400

EAR-2400 - Republish ABS - Survey 202 and form type 1818

---

schemas/business/en/covid_0001.json

Ticket:https://jira.ons.gov.uk/browse/EAR-2419

EAR-2419-Publish BICS wave 109

---

schemas/business/en/covid_0002.json

Publish BICS wave 110

---

schemas/health/en/hms_0001.json

ticket: https://jira.ons.gov.uk/browse/EAR-2423

EAR-2423-Publish HIS to pre-prod

---

schemas/health/en/hms_0001.json

ticket: https://jira.ons.gov.uk/browse/EAR-2423

Republish HIS EAR-2423

---

schemas/business/en/covid_0001.json

https://jira.ons.gov.uk/browse/EAR-2429

EAR-2429 - Publish BICS Wave 111 - Survey ID 283 and Form type 0001

---

schemas/business/en/covid_0002.json

EAR-2433 BICS Wave 112

---

schemas/business/en/abres_0015.json
schemas/business/en/abres_0016.json
schemas/business/en/abres_0017.json
schemas/business/en/abres_0019.json

EAR 2437 Publish BRES

---

.github/workflows/pull_request.yml

Updates actions to to the latest available versions in order to fix deprecation warnings.
Check that actions are still working and that nothing has been missed.

Update actions versions

---

schemas/business/en/covid_0001.json
schemas/health/en/hms_0001.json

EAR-2442-Publish-BICS-NHS

---

schemas/business/en/abres_0015.json
schemas/business/en/abres_0016.json
schemas/business/en/abres_0017.json
schemas/business/en/abres_0019.json

Publish BRES to pre prod
ticket:https://jira.ons.gov.uk/browse/EAR-2445

EAR-2445 Publish Bres to pre prod

---

schemas/business/en/covid_0002.json

EAR 2447 Publish BICS Wave 114

---

schemas/business/en/covid_0001.json

EAR-2457 BICS wave 115

---

schemas/business/en/covid_0002.json

publish BICS wave 116

---

schemas/business/en/covid_0001.json

Publish the new BICS Wave 117 
ticket: https://jira.ons.gov.uk/browse/EAR-2481

EAR 2481 Publish BICS Wave 117

---

schemas/health/en/hms_0001.json

Publish HIS to pre-prod 
ticket: https://jira.ons.gov.uk/browse/EAR-2496

Publish HIS

---

schemas/business/en/covid_0001.json

Publish BICS Wave 119
https://jira.ons.gov.uk/browse/EAR-2518

BICS Wave 119

---

schemas/business/en/covid_0001.json

https://jira.ons.gov.uk/browse/EAR-2537

Publish BICS Wave 121 - Survey ID 283 and Form type 0001

---

schemas/business/en/covid_0002.json

https://jira.ons.gov.uk/browse/EAR-2545

EAR-2545 - Publish BICS wave 122 - Survey ID 283 and Form type 0002

---

schemas/business/en/covid_0001.json

Publish BICS Wave 123 
https://jira.ons.gov.uk/browse/EAR-2553

Publish BICS Wave 123

---

schemas/business/en/lcree_0009.json
schemas/business/en/lcree_0010.json

EAR-2567 - Update LCREE GB & NI schemas

---

schemas/business/en/covid_0001.json

EAR 2568 Publish BICS wave 125

---

schemas/business/en/lcree_0009.json
schemas/business/en/lcree_0010.json

EAR 2567 Publish LCREE

---

schemas/business/en/covid_0002.json

BICS Wave 126

---

schemas/business/en/covid_0001.json

EAR 2594 Publish BICS Wave 127

---

schemas/business/en/ukis_0001.json
schemas/business/en/ukis_0002.json

Publish UKIS: https://jira.ons.gov.uk/browse/EAR-2600

Publish UKIS

---

schemas/business/en/1_0005.json

Publish MWSS:  https://jira.ons.gov.uk/browse/EAR-2599

Publish MWSS

---

schemas/business/en/abs_1802.json
schemas/business/en/abs_1804.json
schemas/business/en/abs_1806.json
schemas/business/en/abs_1808.json
schemas/business/en/abs_1810.json
schemas/business/en/abs_1812.json
schemas/business/en/abs_1814.json
schemas/business/en/abs_1818.json
schemas/business/en/abs_1820.json
schemas/business/en/abs_1824.json

https://jira.ons.gov.uk/browse/EAR-2595

EAR-2595 - Publish ABS form types - Survey ID 202 - Part 1

---

schemas/business/en/abs_1805.json
schemas/business/en/abs_1819.json
schemas/business/en/abs_1825.json
schemas/business/en/abs_1826.json
schemas/business/en/abs_1862.json
schemas/business/en/abs_1863.json
schemas/business/en/abs_1864.json
schemas/business/en/abs_1865.json
schemas/business/en/abs_1874.json
schemas/business/en/abs_1875.json

Publish ABS form types - Survey ID 202 - Part 2

---

schemas/business/en/abs_1803.json
schemas/business/en/abs_1807.json
schemas/business/en/abs_1809.json
schemas/business/en/abs_1811.json
schemas/business/en/abs_1813.json
schemas/business/en/abs_1817.json
schemas/business/en/abs_1823.json
schemas/business/en/abs_1861.json
schemas/business/en/abs_1873.json

ABS form types 
https://jira.ons.gov.uk/browse/EAR-2598

EAR-2598 - Publish ABS form types - Survey ID 202 - Part 4

---

schemas/business/en/abs_1803.json
schemas/business/en/abs_1867.json

Republish of abs_1803 and abs_1867

EAR-2603 ABS Republish

---

schemas/business/en/covid_0001.json

https://jira.ons.gov.uk/browse/EAR-2608

Publish BICS

---

schemas/business/en/covid_0002.json

EAR-2614 BICS Wave 130

---

schemas/business/en/covid_0001.json

EAR-2624: BICS Wave 135

---

schemas/business/en/sppi_0011.json

EAR-2627-Create-SPPI

---

schemas/business/en/covid_0001.json

Update for BICS Wave 139
As usual

Updated schema for BICS Wave 139

---

schemas/business/en/ipi_0001.json
schemas/business/en/ipi_0002.json

EQS-281: Addition of IPI schemas
